// <auto-generated />
using System;
using BMASoft.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BMASoft.Migrations
{
    [DbContext(typeof(BmaDbContext))]
    [Migration("20201030023916_bank2")]
    partial class bank2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BMASoft.Data.Models.ApAcct", b =>
                {
                    b.Property<int>("ApAcctId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acct1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApAcctId");

                    b.ToTable("ApAccts");
                });

            modelBuilder.Entity("BMASoft.Data.Models.ApDist", b =>
                {
                    b.Property<int>("ApDistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dist1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApDistId");

                    b.ToTable("ApDists");
                });

            modelBuilder.Entity("BMASoft.Data.Models.ApHutang", b =>
                {
                    b.Property<int>("ApHutangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Bayar")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Dokumen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Dpp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeTran")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LPB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PPh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PPn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<decimal>("Sisa")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SldBayar")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SldDisc")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SldSisa")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SldUnpl")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UnApplied")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ApHutangId");

                    b.ToTable("ApHutangs");
                });

            modelBuilder.Entity("BMASoft.Data.Models.ApSuppl", b =>
                {
                    b.Property<int>("ApSupplId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcctPjk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlmtNPWP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Disc1")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Disc2")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Hutang")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Kontak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LstOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.Property<string>("NPWP_Sup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaLengkap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaSup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<string>("Person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provinsi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SldAwal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Telpon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Termin")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TglMasuk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.Property<DateTime?>("TglPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.HasKey("ApSupplId");

                    b.HasIndex("Supplier")
                        .IsUnique()
                        .HasFilter("[Supplier] IS NOT NULL");

                    b.ToTable("ApSuppls");
                });

            modelBuilder.Entity("BMASoft.Data.Models.ApTransD", b =>
                {
                    b.Property<int>("ApTransDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApTransHId")
                        .HasColumnType("int");

                    b.Property<decimal>("Bayar")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DistCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("KodeTran")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Lpb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Sisa")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("ApTransDId");

                    b.HasIndex("ApTransHId");

                    b.ToTable("ApTransDs");
                });

            modelBuilder.Entity("BMASoft.Data.Models.ApTransH", b =>
                {
                    b.Property<int>("ApTransHId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApSupplId")
                        .HasColumnType("int");

                    b.Property<decimal>("Bruto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Bukti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Hutang")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("JthTempo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("JumPPh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("JumPPn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("KdBank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("NamaSup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Netto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NoFaktur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PPh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PPn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Unapplied")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ApTransHId");

                    b.ToTable("ApTransHs");
                });

            modelBuilder.Entity("BMASoft.Data.Models.ArAcct", b =>
                {
                    b.Property<int>("ArAcctId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acct1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArAcctId");

                    b.ToTable("ArAccts");
                });

            modelBuilder.Entity("BMASoft.Data.Models.ArCust", b =>
                {
                    b.Property<int>("ArCustId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcctPjk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlmtKrm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlmtNPWP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Disc1")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Disc2")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Expedisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Golongan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kontak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KotaKrm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LstOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.Property<string>("NPWP_Cust")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaCust")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaLengkap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NonPPN")
                        .HasColumnType("bit");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<decimal>("Piutang")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ProvKirim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provinsi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SldAwal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Telpon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Termin")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TglMasuk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.Property<DateTime?>("TglPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.HasKey("ArCustId");

                    b.HasIndex("Customer")
                        .IsUnique()
                        .HasFilter("[Customer] IS NOT NULL");

                    b.ToTable("ArCusts");
                });

            modelBuilder.Entity("BMASoft.Data.Models.ArDist", b =>
                {
                    b.Property<int>("ArDistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dist1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArDistId");

                    b.ToTable("ArDists");
                });

            modelBuilder.Entity("BMASoft.Data.Models.ArPiutng", b =>
                {
                    b.Property<int>("ArPiutngId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Bayar")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Dokumen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Dpp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeTran")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LPB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PPh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PPn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<decimal>("Sisa")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SldBayar")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SldDisc")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SldSisa")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SldUnpl")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UnApplied")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ArPiutngId");

                    b.ToTable("ArPiutngs");
                });

            modelBuilder.Entity("BMASoft.Data.Models.ArTransD", b =>
                {
                    b.Property<int>("ArTransDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArTransHId")
                        .HasColumnType("int");

                    b.Property<decimal>("Bayar")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DistCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("KodeTran")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Lpb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Sisa")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("ArTransDId");

                    b.HasIndex("ArTransHId");

                    b.ToTable("ArTransDs");
                });

            modelBuilder.Entity("BMASoft.Data.Models.ArTransH", b =>
                {
                    b.Property<int>("ArTransHId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArCustId")
                        .HasColumnType("int");

                    b.Property<decimal>("Bruto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Bukti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("JthTempo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("JumPPh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("JumPPn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("KdBank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("NamaCust")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Netto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NoFaktur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PPh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PPn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<decimal>("Piutang")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Unapplied")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ArTransHId");

                    b.ToTable("ArTransHs");
                });

            modelBuilder.Entity("BMASoft.Data.Models.CbBank", b =>
                {
                    b.Property<int>("CbBankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acctset")
                        .HasColumnType("nvarchar(6)")
                        .HasMaxLength(6);

                    b.Property<DateTime>("ClrDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GrpBank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("KSaldo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("KSldAwal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("KodeBank")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Kurs")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("NmBank")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("NonPpn")
                        .HasColumnType("bit");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SldAWal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CbBankId");

                    b.HasIndex("KodeBank")
                        .IsUnique()
                        .HasFilter("[KodeBank] IS NOT NULL");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("BMASoft.Data.Models.CbGrp", b =>
                {
                    b.Property<int>("CbGrpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Grp")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("NamaGrp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CbGrpId");

                    b.ToTable("CbGrps");
                });

            modelBuilder.Entity("BMASoft.Data.Models.CbSrcCode", b =>
                {
                    b.Property<int>("CbSrcCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GlAcct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grp")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("NamaSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SrcCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CbSrcCodeId");

                    b.ToTable("CbSrcCodes");
                });

            modelBuilder.Entity("BMASoft.Data.Models.CbTransD", b =>
                {
                    b.Property<int>("CbTransDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Bayar")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CbTransHId")
                        .HasColumnType("int");

                    b.Property<string>("GlAcct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("KBayar")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("KJumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("KTerima")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("KValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kurs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoPrj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SrcCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SrcCodeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Terima")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("CbTransDId");

                    b.HasIndex("CbTransHId");

                    b.ToTable("CbTransDs");
                });

            modelBuilder.Entity("BMASoft.Data.Models.CbTransH", b =>
                {
                    b.Property<int>("CbTransHId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acctset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cek")
                        .HasColumnType("bit");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Giro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("KSaldo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeBank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kurs")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<bool>("NonPPN")
                        .HasColumnType("bit");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<string>("Refno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("CbTransHId");

                    b.ToTable("CbTransHs");
                });

            modelBuilder.Entity("BMASoft.Data.Models.CbTransfer", b =>
                {
                    b.Property<int>("CbTransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acctset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cek")
                        .HasColumnType("bit");

                    b.Property<string>("DocNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Giro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("KSaldo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("KValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeBank1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeBank2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kurs")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<bool>("NonPPN")
                        .HasColumnType("bit");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<string>("Refno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("CbTransferId");

                    b.ToTable("CbTransfers");
                });

            modelBuilder.Entity("BMASoft.Data.Models.GlAccount", b =>
                {
                    b.Property<int>("GlAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GlAcct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlDept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GlFisc1")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc10")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc11")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc12")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc2")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc3")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc4")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc5")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc6")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc7")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc8")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc9")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("GlKurs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlNama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GlPost")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GlPreFisc1")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc10")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc11")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc12")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc2")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc3")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc4")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc5")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc6")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc7")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc8")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc9")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlSaldo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlSldAwal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("GlStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GlTipe")
                        .HasColumnType("int");

                    b.Property<string>("NamaLengkap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipeGl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GlAccountId");

                    b.ToTable("GlAccounts");
                });

            modelBuilder.Entity("BMASoft.Data.Models.GlCode", b =>
                {
                    b.Property<int>("GlCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KodeGl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaGl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GlCodeId");

                    b.ToTable("GlCodes");
                });

            modelBuilder.Entity("BMASoft.Data.Models.GlTransD", b =>
                {
                    b.Property<int>("GlTransDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Debet")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("GlTransHId")
                        .HasColumnType("int");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Kredit")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("GlTransDId");

                    b.HasIndex("GlTransHId");

                    b.ToTable("GlTransDs");
                });

            modelBuilder.Entity("BMASoft.Data.Models.GlTransH", b =>
                {
                    b.Property<int>("GlTransHId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Debet")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DocNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlMemo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeGl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Kredit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Kurs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("GlTransHId");

                    b.ToTable("GlTransHs");
                });

            modelBuilder.Entity("BMASoft.Data.Models.IcAcct", b =>
                {
                    b.Property<int>("IcAcctId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acct1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IcAcctId");

                    b.ToTable("IcAccts");
                });

            modelBuilder.Entity("BMASoft.Data.Models.IcAltItem", b =>
                {
                    b.Property<int>("IcAltItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BefNetto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CostAwal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CostMethod")
                        .HasColumnType("int");

                    b.Property<string>("Divisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HrgJual")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HrgNetto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JnsBrng")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastNetto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QtyPo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SaldoAwal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Satuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SerialNo")
                        .HasColumnType("bit");

                    b.Property<decimal>("StdPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("TglPost")
                        .HasColumnType("datetime2");

                    b.HasKey("IcAltItemId");

                    b.ToTable("IcAltItems");
                });

            modelBuilder.Entity("BMASoft.Data.Models.IcCat", b =>
                {
                    b.Property<int>("IcCatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cat1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cat2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cat3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cat4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cat5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cat6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IcCatId");

                    b.ToTable("IcCats");
                });

            modelBuilder.Entity("BMASoft.Data.Models.IcDiv", b =>
                {
                    b.Property<int>("IcDivId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Divisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaDiv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IcDivId");

                    b.ToTable("IcDivs");
                });

            modelBuilder.Entity("BMASoft.Data.Models.IcItem", b =>
                {
                    b.Property<int>("IcItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BefNetto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CostAwal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CostMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Divisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HrgJual")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HrgNetto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HrgUsd")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JnsBrng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastNetto")
                        .HasColumnType("datetime2");

                    b.Property<string>("NamaItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaLengkap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QtyPo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SaldoAwal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Satuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SerialNo")
                        .HasColumnType("bit");

                    b.Property<decimal>("StdPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("TglPost")
                        .HasColumnType("datetime2");

                    b.HasKey("IcItemId");

                    b.ToTable("IcItems");
                });

            modelBuilder.Entity("BMASoft.Data.Models.IcLokasi", b =>
                {
                    b.Property<int>("IcLokasiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaLokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telpon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IcLokasiId");

                    b.ToTable("Iclokasis");
                });

            modelBuilder.Entity("BMASoft.Data.Models.IcTransD", b =>
                {
                    b.Property<int>("IcTransDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("IcTransHId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokasi2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoFaktur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoSj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QtyBo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QtyShp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Satuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("IcTransDId");

                    b.HasIndex("IcTransHId");

                    b.ToTable("IcTransDs");
                });

            modelBuilder.Entity("BMASoft.Data.Models.IcTransH", b =>
                {
                    b.Property<int>("IcTransHId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokasi2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoFaktur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoSj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("IcTransHId");

                    b.ToTable("IcTransHs");
                });

            modelBuilder.Entity("BMASoft.Data.Models.IrTransD", b =>
                {
                    b.Property<int>("IrTransDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("IrTransHId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("JumDpp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoLpb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Persen")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QtyBo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Satuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("IrTransDId");

                    b.HasIndex("IrTransHId");

                    b.ToTable("IrTransDs");
                });

            modelBuilder.Entity("BMASoft.Data.Models.IrTransH", b =>
                {
                    b.Property<int>("IrTransHId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DPayment")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("JthTempo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaSup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoLpb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoPrj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Ongkos")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<decimal>("Ppn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PpnPersen")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tagihan")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TtlJumlah")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("IrTransHId");

                    b.ToTable("IrTransHs");
                });

            modelBuilder.Entity("BMASoft.Data.Models.OeTransD", b =>
                {
                    b.Property<int>("OeTransDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HrgCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("JumDpp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoLpb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoSJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OeTransHId")
                        .HasColumnType("int");

                    b.Property<decimal>("Persen")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QtyBo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Satuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("OeTransDId");

                    b.HasIndex("OeTransHId");

                    b.ToTable("OeTransDs");
                });

            modelBuilder.Entity("BMASoft.Data.Models.OeTransH", b =>
                {
                    b.Property<int>("OeTransHId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DPayment")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("JthTempo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaCust")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoLpb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoPrj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoSJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Ongkos")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<decimal>("Ppn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PpnPersen")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Tagihan")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TtlJumlah")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("OeTransHId");

                    b.ToTable("OeTransHs");
                });

            modelBuilder.Entity("BMASoft.Data.Models.ApTransD", b =>
                {
                    b.HasOne("BMASoft.Data.Models.ApTransH", "ApTransH")
                        .WithMany("ApTransDs")
                        .HasForeignKey("ApTransHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BMASoft.Data.Models.ArTransD", b =>
                {
                    b.HasOne("BMASoft.Data.Models.ArTransH", "ArTransH")
                        .WithMany("ArTransDs")
                        .HasForeignKey("ArTransHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BMASoft.Data.Models.CbTransD", b =>
                {
                    b.HasOne("BMASoft.Data.Models.CbTransH", "CbTransH")
                        .WithMany("CbTransDs")
                        .HasForeignKey("CbTransHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BMASoft.Data.Models.GlTransD", b =>
                {
                    b.HasOne("BMASoft.Data.Models.GlTransH", "GlTransH")
                        .WithMany("GlTransDs")
                        .HasForeignKey("GlTransHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BMASoft.Data.Models.IcTransD", b =>
                {
                    b.HasOne("BMASoft.Data.Models.IcTransH", "IcTransH")
                        .WithMany("IcTransDs")
                        .HasForeignKey("IcTransHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BMASoft.Data.Models.IrTransD", b =>
                {
                    b.HasOne("BMASoft.Data.Models.IrTransH", "IrTransH")
                        .WithMany("IrTransDs")
                        .HasForeignKey("IrTransHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BMASoft.Data.Models.OeTransD", b =>
                {
                    b.HasOne("BMASoft.Data.Models.OeTransH", "OeTransH")
                        .WithMany("OeTransDs")
                        .HasForeignKey("OeTransHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
